### ISSUE TITLE
Create Extension Icon

### ISSUE THREAD

**Issue by andreylipattsev** [tharsheblows/cloudfest-cookies#2]

**Comment by airsplitter** [comment]
![Image](https://user-images.githubusercontent.com/102050982/226113354-b9098871-ba00-4217-b89e-27ce33791c4b.png)

**Comment by tharsheblows** [comment]
[Merged to main ](https://github.com/tharsheblows/cloudfest-cookies/pull/4) and it looks awesome!

**Comment by airsplitter** [comment]
![Image](https://user-images.githubusercontent.com/102050982/226120988-c1901983-2e2c-415d-8341-a763f785e794.png)

simplified for better appearance at small size.
