### ISSUE TITLE
Create final presentation

### ISSUE THREAD

**Issue by andreylipattsev** [tharsheblows/cloudfest-cookies#9]

**Comment by benjaminburkhardt** [comment]
Started working in the final PPT slides.
# Storyline
-  You want to play Mario Kart, but cannot login? Damn, that's bad! :-(
- This is what might happen soon if povvides do not update their platforms!
- What did we do? 
- What is the Google Privacy Sandbox?
- Call for action!

**Comment by benjaminburkhardt** [comment]
https://github.com/tharsheblows/cloudfest-cookies/blob/main/docs/pitch.pdf

**Comment by benjaminburkhardt** [comment]
https://github.com/tharsheblows/cloudfest-cookies/blob/main/docs/pitch.pdf
